# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nghianguyen/hdd/tmp/copy

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nghianguyen/hdd/tmp/copy

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nghianguyen/hdd/tmp/copy/CMakeFiles /home/nghianguyen/hdd/tmp/copy//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nghianguyen/hdd/tmp/copy/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named clip

# Build rule for target.
clip: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clip
.PHONY : clip

# fast build rule for target.
clip/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clip.dir/build.make CMakeFiles/clip.dir/build
.PHONY : clip/fast

#=============================================================================
# Target rules for targets named copy

# Build rule for target.
copy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 copy
.PHONY : copy

# fast build rule for target.
copy/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/copy.dir/build.make CMakeFiles/copy.dir/build
.PHONY : copy/fast

clip/clip.o: clip/clip.cpp.o
.PHONY : clip/clip.o

# target to build an object file
clip/clip.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clip.dir/build.make CMakeFiles/clip.dir/clip/clip.cpp.o
.PHONY : clip/clip.cpp.o

clip/clip.i: clip/clip.cpp.i
.PHONY : clip/clip.i

# target to preprocess a source file
clip/clip.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clip.dir/build.make CMakeFiles/clip.dir/clip/clip.cpp.i
.PHONY : clip/clip.cpp.i

clip/clip.s: clip/clip.cpp.s
.PHONY : clip/clip.s

# target to generate assembly for a file
clip/clip.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clip.dir/build.make CMakeFiles/clip.dir/clip/clip.cpp.s
.PHONY : clip/clip.cpp.s

clip/clip_x11.o: clip/clip_x11.cpp.o
.PHONY : clip/clip_x11.o

# target to build an object file
clip/clip_x11.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clip.dir/build.make CMakeFiles/clip.dir/clip/clip_x11.cpp.o
.PHONY : clip/clip_x11.cpp.o

clip/clip_x11.i: clip/clip_x11.cpp.i
.PHONY : clip/clip_x11.i

# target to preprocess a source file
clip/clip_x11.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clip.dir/build.make CMakeFiles/clip.dir/clip/clip_x11.cpp.i
.PHONY : clip/clip_x11.cpp.i

clip/clip_x11.s: clip/clip_x11.cpp.s
.PHONY : clip/clip_x11.s

# target to generate assembly for a file
clip/clip_x11.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clip.dir/build.make CMakeFiles/clip.dir/clip/clip_x11.cpp.s
.PHONY : clip/clip_x11.cpp.s

copy.o: copy.cpp.o
.PHONY : copy.o

# target to build an object file
copy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/copy.dir/build.make CMakeFiles/copy.dir/copy.cpp.o
.PHONY : copy.cpp.o

copy.i: copy.cpp.i
.PHONY : copy.i

# target to preprocess a source file
copy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/copy.dir/build.make CMakeFiles/copy.dir/copy.cpp.i
.PHONY : copy.cpp.i

copy.s: copy.cpp.s
.PHONY : copy.s

# target to generate assembly for a file
copy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/copy.dir/build.make CMakeFiles/copy.dir/copy.cpp.s
.PHONY : copy.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... clip"
	@echo "... copy"
	@echo "... clip/clip.o"
	@echo "... clip/clip.i"
	@echo "... clip/clip.s"
	@echo "... clip/clip_x11.o"
	@echo "... clip/clip_x11.i"
	@echo "... clip/clip_x11.s"
	@echo "... copy.o"
	@echo "... copy.i"
	@echo "... copy.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

